sudo: required

branches:
  only:
    - master

cache:
  directories:
    - $HOME/cache

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in myEmailKey.enc -out myEmailKey -d
  - eval "$(ssh-agent -s)"
  - chmod 600 myEmailKey
  - ssh-add myEmailKey
  #- docker build -t webapp:test -f dockerfile/test .
script:
  - docker build -t webapp:test -f dockerfile/test .
  - docker run -it --rm -v $HOME/cache:/root/.nuget/packages webapp:test
  - docker run -it --rm -v $PWD/publish:/root/publish -v $PWD/packages:/root/.nuget/packages webapp:test
  - docker build -t webapp:release -f dockerfile/release .

after_success:
  - docker tag webapp:release eric3475/webapp:latest
  - docker login -u=$DOCKER_USERNAME -p=$DOCKER_PASSWORD
  - docker push eric3475/webapp:latest
  - scp -o StrictHostKeyChecking=no ./scripts/getReleaseFromDockerHubAndStart.sh u1440590@159.203.33.172:~/
  - ssh u1440590@159.203.33.172 "chmod +x getReleaseFromDockerHubAndStart.sh"
  - ssh u1440590@159.203.33.172 "sh getReleaseFromDockerHubAndStart.sh"
